name = "Nanocompore_v2_manuscript_analysis"
authors = ["Mihail Zdravkov <mail@mzdravkov.com>"]
uuid = "17e506b2-5e4a-4142-ad25-36439fc8fd3b"
version = "0.0.1"


[deps]
AlgebraOfGraphics = "cbdf2221-f076-402e-a563-3d30da359d67"
Associations = "614afb3a-e278-4863-8805-9959372b9ec2"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
ConfSets = "aad220d6-53bb-4824-ac0f-9e0382ca6dbc"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
FASTX = "c2308a5c-f048-11e8-3e8a-31650f418d12"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
GenomicAnnotations = "4f8a0a0a-376d-5ac0-ab14-e88793df67f0"
MLBase = "f0e99cf1-93fa-52ec-9ecc-5026115318e0"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
Peaks = "18e31ff7-3703-566c-8e60-38913d67486b"
SQLite = "0aa819cd-b072-5ff4-a722-6bc24af294d9"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
Typst_jll = "eb4b1da6-20f6-5c66-9826-fdb8ad410d0e"
UMAP = "c4f8c510-2410-5be4-91d7-4fbaeb39457e"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
AlgebraOfGraphics = "0.10.2"
Associations = "4.5.0"
CSV = "0.10.15"
CairoMakie = "0.13.2"
CategoricalArrays = "0.10.8"
Clustering = "0.15.8"
ConfSets = "0.1.1"
DataFrames = "1.7.0"
FASTX = "2.1.7"
FileIO = "1.17.1"
GenomicAnnotations = "0.4.5"
MLBase = "0.9.2"
MultivariateStats = "0.10.3"
Peaks = "0.5.3"
SQLite = "1.6.1"
StatsBase = "0.34.4"
StatsPlots = "0.15.7"
Typst_jll = "0.13.0"
UMAP = "0.1.11"
Unitful = "1.22.0"

